name: Get Diversions v2

on:
  schedule:
    - cron: '*/30 * * * *'  # Spouští se po 30 minutách 
  workflow_dispatch:  # Přidá možnost manuálního spuštění

jobs:
  save_diversions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Checkout hidden-data repository
        uses: actions/checkout@v2
        with:
          repository: psimonek/hidden-data
          token: ${{ secrets.YML_TOKEN }}
          path: hidden-data
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python hidden-data/get-diversions/get-diversions_v2.py  

      - name: Move diversions.json to public directory
        run: mv diversions_v2.json get-diversions/diversions_v2.json  # Přesun souboru do veřejné složky

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add -f get-diversions/diversions_v2.json  # Upravena cesta k souboru
          git commit -m "Update diversions_v2.json" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/psimonek/mhd-brno-test.git HEAD:main
